# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2020-05-05 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200505_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tz',
            field=models.CharField(max_length=32),
        ),
    ]
